org.gradle.caching=true
org.gradle.configureondemand=true
org.gradle.configuration-cache=true
org.gradle.jvmargs=-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.problems.report=false

description=PlotSquared, a land and world management plugin for Minecraft.
group=co.crystaldev
version=3.809.1-SNAPSHOT
