name: "Deploy"

on:
  workflow_dispatch: # manually triggered

jobs:
  build-and-deploy:
    if: github.repository_owner == 'crystal-development-llc' && github.ref_name == '1.8.8-patched'
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      # https://github.com/actions/checkout/releases
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      # https://github.com/actions/setup-java/releases
      - uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
        with:
          distribution: temurin
          java-version: 21

      # https://github.com/gradle/actions/releases
      - uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v5.0.0
        with:
          validate-wrappers: true
          gradle-version: wrapper
          cache-disabled: false

      - run: ./gradlew clean build --no-configuration-cache --full-stacktrace

      - run: ./gradlew publishAllPublicationsToAlpineCloudRepository --no-configuration-cache --full-stacktrace
        env:
          ALPINE_MAVEN_NAME: ${{ secrets.ALPINE_MAVEN_NAME }}
          ALPINE_MAVEN_SECRET: ${{ secrets.ALPINE_MAVEN_SECRET }}
